"""se quita relacion de categorias con usuarios y se crea tablas y relaciones de Conceptos y etiquetas

Revision ID: 0980d5c838a5
Revises: 6aa0a7bdfa03
Create Date: 2026-08-19 22:09:17.418673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0980d5c838a5'
down_revision: Union[str, Sequence[str], None] = '6aa0a7bdfa03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConceptosGastos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('NombreConcepto', sa.String(length=200), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_ConceptosGastos_Id'), 'ConceptosGastos', ['Id'], unique=False)
    op.create_table('EtiquetasGastos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('NombreEtiqueta', sa.String(length=200), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_EtiquetasGastos_Id'), 'EtiquetasGastos', ['Id'], unique=False)
    op.create_table('MovimientosGastosConceptos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('MovimientoGastoId', sa.Integer(), nullable=False),
    sa.Column('ConceptoId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ConceptoId'], ['ConceptosGastos.Id'], ),
    sa.ForeignKeyConstraint(['MovimientoGastoId'], ['MovimientosGastos.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('MovimientoGastoId', 'ConceptoId', name='uq_movimiento_gasto_concepto')
    )
    op.create_index(op.f('ix_MovimientosGastosConceptos_ConceptoId'), 'MovimientosGastosConceptos', ['ConceptoId'], unique=False)
    op.create_index(op.f('ix_MovimientosGastosConceptos_Id'), 'MovimientosGastosConceptos', ['Id'], unique=False)
    op.create_index(op.f('ix_MovimientosGastosConceptos_MovimientoGastoId'), 'MovimientosGastosConceptos', ['MovimientoGastoId'], unique=False)
    op.create_table('MovimientosGastosEtiquetas',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('MovimientoGastoId', sa.Integer(), nullable=False),
    sa.Column('EtiquetaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EtiquetaId'], ['EtiquetasGastos.Id'], ),
    sa.ForeignKeyConstraint(['MovimientoGastoId'], ['MovimientosGastos.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('MovimientoGastoId', 'EtiquetaId', name='uq_movimiento_gasto_etiqueta')
    )
    op.create_index(op.f('ix_MovimientosGastosEtiquetas_EtiquetaId'), 'MovimientosGastosEtiquetas', ['EtiquetaId'], unique=False)
    op.create_index(op.f('ix_MovimientosGastosEtiquetas_Id'), 'MovimientosGastosEtiquetas', ['Id'], unique=False)
    op.create_index(op.f('ix_MovimientosGastosEtiquetas_MovimientoGastoId'), 'MovimientosGastosEtiquetas', ['MovimientoGastoId'], unique=False)
    op.drop_index(op.f('ix_CategoriasGastos_UsuarioId'), table_name='CategoriasGastos')
    op.drop_constraint(op.f('CategoriasGastos_UsuarioId_fkey'), 'CategoriasGastos', type_='foreignkey')
    op.drop_column('CategoriasGastos', 'UsuarioId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CategoriasGastos', sa.Column('UsuarioId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('CategoriasGastos_UsuarioId_fkey'), 'CategoriasGastos', 'Usuarios', ['UsuarioId'], ['Id'])
    op.create_index(op.f('ix_CategoriasGastos_UsuarioId'), 'CategoriasGastos', ['UsuarioId'], unique=False)
    op.drop_index(op.f('ix_MovimientosGastosEtiquetas_MovimientoGastoId'), table_name='MovimientosGastosEtiquetas')
    op.drop_index(op.f('ix_MovimientosGastosEtiquetas_Id'), table_name='MovimientosGastosEtiquetas')
    op.drop_index(op.f('ix_MovimientosGastosEtiquetas_EtiquetaId'), table_name='MovimientosGastosEtiquetas')
    op.drop_table('MovimientosGastosEtiquetas')
    op.drop_index(op.f('ix_MovimientosGastosConceptos_MovimientoGastoId'), table_name='MovimientosGastosConceptos')
    op.drop_index(op.f('ix_MovimientosGastosConceptos_Id'), table_name='MovimientosGastosConceptos')
    op.drop_index(op.f('ix_MovimientosGastosConceptos_ConceptoId'), table_name='MovimientosGastosConceptos')
    op.drop_table('MovimientosGastosConceptos')
    op.drop_index(op.f('ix_EtiquetasGastos_Id'), table_name='EtiquetasGastos')
    op.drop_table('EtiquetasGastos')
    op.drop_index(op.f('ix_ConceptosGastos_Id'), table_name='ConceptosGastos')
    op.drop_table('ConceptosGastos')
    # ### end Alembic commands ###
