"""se quita valor unico

Revision ID: 0f41a8cb6b7b
Revises: 7b2c9d4e1f6a
Create Date: 2026-09-14 23:58:40.833325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f41a8cb6b7b'
down_revision: Union[str, Sequence[str], None] = '7b2c9d4e1f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
