"""agregar Relacion entre estadisticas y movimientos_gastos

Revision ID: 1055816ad81b
Revises: 5e6e08cc5e38
Create Date: 2026-09-13 22:43:54.291990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1055816ad81b'
down_revision: Union[str, Sequence[str], None] = '5e6e08cc5e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EstadisticasModelos', sa.Column('IdMovimiento', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_EstadisticasModelos_IdMovimiento'), 'EstadisticasModelos', ['IdMovimiento'], unique=False)
    op.create_foreign_key(None, 'EstadisticasModelos', 'MovimientosGastos', ['IdMovimiento'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EstadisticasModelos', type_='foreignkey')
    op.drop_index(op.f('ix_EstadisticasModelos_IdMovimiento'), table_name='EstadisticasModelos')
    op.drop_column('EstadisticasModelos', 'IdMovimiento')
    # ### end Alembic commands ###
