"""relacion_usuarios_entidades_usuario

Revision ID: 12fd5cc9bdb4
Revises: 84081257792e
Create Date: 2026-10-01 22:41:51.643496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12fd5cc9bdb4'
down_revision: Union[str, Sequence[str], None] = '84081257792e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EntidadesUsuarios', sa.Column('UsuarioId', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_EntidadesUsuarios_UsuarioId'), 'EntidadesUsuarios', ['UsuarioId'], unique=False)
    op.create_foreign_key(None, 'EntidadesUsuarios', 'Usuarios', ['UsuarioId'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EntidadesUsuarios', type_='foreignkey')
    op.drop_index(op.f('ix_EntidadesUsuarios_UsuarioId'), table_name='EntidadesUsuarios')
    op.drop_column('EntidadesUsuarios', 'UsuarioId')
    # ### end Alembic commands ###
