"""models_movimientos_gastos_imagenes

Revision ID: 1eacd71d0576
Revises: 5397860d938b
Create Date: 2026-08-11 22:21:33.914469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eacd71d0576'
down_revision: Union[str, Sequence[str], None] = '5397860d938b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MovimientosGastos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('TotalGasto', sa.Integer(), nullable=False),
    sa.Column('IvaDiez', sa.Integer(), nullable=False),
    sa.Column('IvaCinco', sa.Integer(), nullable=False),
    sa.Column('FechaGasto', sa.Date(), nullable=False),
    sa.Column('TipoRegistro', sa.Enum('Manual', 'Automatico', 'Hibrido', name='tiporegistroenum'), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('CategoriaId', sa.Integer(), nullable=False),
    sa.Column('EmpresaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CategoriaId'], ['CategoriasGastos.Id'], ),
    sa.ForeignKeyConstraint(['EmpresaId'], ['Empresas.Id'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_MovimientosGastos_CategoriaId'), 'MovimientosGastos', ['CategoriaId'], unique=False)
    op.create_index(op.f('ix_MovimientosGastos_EmpresaId'), 'MovimientosGastos', ['EmpresaId'], unique=False)
    op.create_index(op.f('ix_MovimientosGastos_Id'), 'MovimientosGastos', ['Id'], unique=False)
    op.create_index(op.f('ix_MovimientosGastos_UsuarioId'), 'MovimientosGastos', ['UsuarioId'], unique=False)
    op.create_table('MovimientosGastosImagenes',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UrlImagen', sa.String(length=255), nullable=False),
    sa.Column('ReferenciaCola', sa.Integer(), nullable=False),
    sa.Column('MovimientoGastoId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MovimientoGastoId'], ['MovimientosGastos.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_MovimientosGastosImagenes_Id'), 'MovimientosGastosImagenes', ['Id'], unique=False)
    op.create_index(op.f('ix_MovimientosGastosImagenes_MovimientoGastoId'), 'MovimientosGastosImagenes', ['MovimientoGastoId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_MovimientosGastosImagenes_MovimientoGastoId'), table_name='MovimientosGastosImagenes')
    op.drop_index(op.f('ix_MovimientosGastosImagenes_Id'), table_name='MovimientosGastosImagenes')
    op.drop_table('MovimientosGastosImagenes')
    op.drop_index(op.f('ix_MovimientosGastos_UsuarioId'), table_name='MovimientosGastos')
    op.drop_index(op.f('ix_MovimientosGastos_Id'), table_name='MovimientosGastos')
    op.drop_index(op.f('ix_MovimientosGastos_EmpresaId'), table_name='MovimientosGastos')
    op.drop_index(op.f('ix_MovimientosGastos_CategoriaId'), table_name='MovimientosGastos')
    op.drop_table('MovimientosGastos')
    # ### end Alembic commands ###
