"""codigo_reporte se deja de usar

Revision ID: 227fa2a2a0ac
Revises: 7f4a2c9d1e6b
Create Date: 2026-09-03 15:26:59.706466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227fa2a2a0ac'
down_revision: Union[str, Sequence[str], None] = '7f4a2c9d1e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ImagenesReportadasUrls_UrlImagen_key'), 'ImagenesReportadasUrls', type_='unique')
    op.drop_index(op.f('ix_ImagenesReportadasUrls_CodigoReporte'), table_name='ImagenesReportadasUrls')
    op.drop_column('ImagenesReportadasUrls', 'CodigoReporte')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImagenesReportadasUrls', sa.Column('CodigoReporte', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_ImagenesReportadasUrls_CodigoReporte'), 'ImagenesReportadasUrls', ['CodigoReporte'], unique=False)
    op.create_unique_constraint(op.f('ImagenesReportadasUrls_UrlImagen_key'), 'ImagenesReportadasUrls', ['UrlImagen'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
