"""campo_numerofactura_movimientos_gastos

Revision ID: 2a49594f3da7
Revises: 1eacd71d0576
Create Date: 2026-08-11 22:31:48.773593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a49594f3da7'
down_revision: Union[str, Sequence[str], None] = '1eacd71d0576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MovimientosGastos', sa.Column('NumeroFactura', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_movimientosgastos_empresa_numerofactura', 'MovimientosGastos', ['EmpresaId', 'NumeroFactura'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_movimientosgastos_empresa_numerofactura', 'MovimientosGastos', type_='unique')
    op.drop_column('MovimientosGastos', 'NumeroFactura')
    # ### end Alembic commands ###
