"""se agrega registro de errores de pendientes

Revision ID: 316608371b88
Revises: a6f6bf8014f6
Create Date: 2026-09-14 16:10:08.994133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316608371b88'
down_revision: Union[str, Sequence[str], None] = 'a6f6bf8014f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ErroresProcesamientoImagenesPendientes',
    sa.Column('IdRegistro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ImagenesPendientesId', sa.Integer(), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('TipoError', sa.Enum('Modelo', 'EstructuraDatos', 'RegistroDato', name='tipoerrorenum'), nullable=False),
    sa.Column('Error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ImagenesPendientesId'], ['ImagenesPendientes.Id'], ),
    sa.PrimaryKeyConstraint('IdRegistro')
    )
    op.create_index(op.f('ix_ErroresProcesamientoImagenesPendientes_IdRegistro'), 'ErroresProcesamientoImagenesPendientes', ['IdRegistro'], unique=False)
    op.create_index(op.f('ix_ErroresProcesamientoImagenesPendientes_ImagenesPendientesId'), 'ErroresProcesamientoImagenesPendientes', ['ImagenesPendientesId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ErroresProcesamientoImagenesPendientes_ImagenesPendientesId'), table_name='ErroresProcesamientoImagenesPendientes')
    op.drop_index(op.f('ix_ErroresProcesamientoImagenesPendientes_IdRegistro'), table_name='ErroresProcesamientoImagenesPendientes')
    op.drop_table('ErroresProcesamientoImagenesPendientes')
    # ### end Alembic commands ###
