"""registro de control de errores en modelos

Revision ID: 3828b1423ef5
Revises: d7199eeb5703
Create Date: 2026-08-18 22:33:38.070147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3828b1423ef5'
down_revision: Union[str, Sequence[str], None] = 'd7199eeb5703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ErroresModelos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Proceso', sa.String(length=255), nullable=False),
    sa.Column('NombreModelo', sa.String(length=255), nullable=False),
    sa.Column('RespuestaError', sa.Text(), nullable=True),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_ErroresModelos_Id'), 'ErroresModelos', ['Id'], unique=False)
    op.create_index(op.f('ix_ErroresModelos_NombreModelo'), 'ErroresModelos', ['NombreModelo'], unique=False)
    op.create_index(op.f('ix_ErroresModelos_Proceso'), 'ErroresModelos', ['Proceso'], unique=False)
    op.create_index(op.f('ix_ErroresModelos_UsuarioId'), 'ErroresModelos', ['UsuarioId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ErroresModelos_UsuarioId'), table_name='ErroresModelos')
    op.drop_index(op.f('ix_ErroresModelos_Proceso'), table_name='ErroresModelos')
    op.drop_index(op.f('ix_ErroresModelos_NombreModelo'), table_name='ErroresModelos')
    op.drop_index(op.f('ix_ErroresModelos_Id'), table_name='ErroresModelos')
    op.drop_table('ErroresModelos')
    # ### end Alembic commands ###
