"""union entre movimientos e imagenes pendientes

Revision ID: 391983d916c9
Revises: dfdfbafa5c54
Create Date: 2026-08-21 19:34:03.766254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391983d916c9'
down_revision: Union[str, Sequence[str], None] = 'dfdfbafa5c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImagenesPendientes', sa.Column('Procesado', sa.Boolean(), nullable=True))
    op.add_column('ImagenesPendientes', sa.Column('FechaProcesado', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ImagenesPendientes', sa.Column('MovimientoId', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ImagenesPendientes_MovimientoId'), 'ImagenesPendientes', ['MovimientoId'], unique=False)
    op.create_foreign_key(None, 'ImagenesPendientes', 'MovimientosGastos', ['MovimientoId'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ImagenesPendientes', type_='foreignkey')
    op.drop_index(op.f('ix_ImagenesPendientes_MovimientoId'), table_name='ImagenesPendientes')
    op.drop_column('ImagenesPendientes', 'MovimientoId')
    op.drop_column('ImagenesPendientes', 'FechaProcesado')
    op.drop_column('ImagenesPendientes', 'Procesado')
    # ### end Alembic commands ###
