"""se quita el usuario de errores modelos

Revision ID: 39783cf809d9
Revises: 3828b1423ef5
Create Date: 2026-08-18 22:46:34.748271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39783cf809d9'
down_revision: Union[str, Sequence[str], None] = '3828b1423ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ErroresModelos_UsuarioId'), table_name='ErroresModelos')
    op.drop_constraint(op.f('ErroresModelos_UsuarioId_fkey'), 'ErroresModelos', type_='foreignkey')
    op.drop_column('ErroresModelos', 'UsuarioId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ErroresModelos', sa.Column('UsuarioId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('ErroresModelos_UsuarioId_fkey'), 'ErroresModelos', 'Usuarios', ['UsuarioId'], ['Id'])
    op.create_index(op.f('ix_ErroresModelos_UsuarioId'), 'ErroresModelos', ['UsuarioId'], unique=False)
    # ### end Alembic commands ###
