"""cambios en ImagenesPendientes

Revision ID: 3bb57e759a81
Revises: 5e1cadf3aaf6
Create Date: 2026-08-14 13:57:52.668916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb57e759a81'
down_revision: Union[str, Sequence[str], None] = '5e1cadf3aaf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImagenesPendientes', sa.Column('Motivo', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ImagenesPendientes', 'Motivo')
    # ### end Alembic commands ###
