"""estado_fecha_registro_medio_pago_usuario

Revision ID: 3d3a4d8250b9
Revises: 12fd5cc9bdb4
Create Date: 2026-10-01 22:56:32.512584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3a4d8250b9'
down_revision: Union[str, Sequence[str], None] = '12fd5cc9bdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MediosPagosUsuarios', sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('MediosPagosUsuarios', sa.Column('IsActive', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MediosPagosUsuarios', 'IsActive')
    op.drop_column('MediosPagosUsuarios', 'FechaRegistro')
    # ### end Alembic commands ###
