"""estructuras de tablas para estadisticas

Revision ID: 3ffb4ae95ac8
Revises: a1436cd6d725
Create Date: 2026-09-11 14:49:38.741933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffb4ae95ac8'
down_revision: Union[str, Sequence[str], None] = 'a1436cd6d725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EstadisticasModelos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('Origen', sa.Enum('Aplicacion', 'Jobs', name='origenestadisticaenum'), nullable=False),
    sa.Column('Estado', sa.Enum('Pendiente', 'Registrada', 'Descartada', name='estadoestadisticaenum'), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_EstadisticasModelos_Id'), 'EstadisticasModelos', ['Id'], unique=False)
    op.create_index(op.f('ix_EstadisticasModelos_UsuarioId'), 'EstadisticasModelos', ['UsuarioId'], unique=False)
    op.create_table('EstadisticasModelosDetalle',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EstadisticasModelosId', sa.Integer(), nullable=False),
    sa.Column('TipoOperacion', sa.Enum('Extraccion', 'Clasificacion', name='tipooperacionenum'), nullable=False),
    sa.Column('NombreModelo', sa.String(length=255), nullable=False),
    sa.Column('InputTokens', sa.Integer(), nullable=False),
    sa.Column('OutputTokens', sa.Integer(), nullable=False),
    sa.Column('ThoughtsTokens', sa.Integer(), nullable=False),
    sa.Column('TotalTokens', sa.Integer(), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['EstadisticasModelosId'], ['EstadisticasModelos.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_EstadisticasModelosDetalle_EstadisticasModelosId'), 'EstadisticasModelosDetalle', ['EstadisticasModelosId'], unique=False)
    op.create_index(op.f('ix_EstadisticasModelosDetalle_Id'), 'EstadisticasModelosDetalle', ['Id'], unique=False)
    op.create_table('EstadisticasModelosImagenes',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EstadisticasModelosId', sa.Integer(), nullable=False),
    sa.Column('UrlTemporal', sa.String(length=500), nullable=False),
    sa.Column('UrlsPermanente', sa.String(length=500), nullable=False),
    sa.Column('TamañoImagen', sa.Integer(), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['EstadisticasModelosId'], ['EstadisticasModelos.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_EstadisticasModelosImagenes_EstadisticasModelosId'), 'EstadisticasModelosImagenes', ['EstadisticasModelosId'], unique=False)
    op.create_index(op.f('ix_EstadisticasModelosImagenes_Id'), 'EstadisticasModelosImagenes', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_EstadisticasModelosImagenes_Id'), table_name='EstadisticasModelosImagenes')
    op.drop_index(op.f('ix_EstadisticasModelosImagenes_EstadisticasModelosId'), table_name='EstadisticasModelosImagenes')
    op.drop_table('EstadisticasModelosImagenes')
    op.drop_index(op.f('ix_EstadisticasModelosDetalle_Id'), table_name='EstadisticasModelosDetalle')
    op.drop_index(op.f('ix_EstadisticasModelosDetalle_EstadisticasModelosId'), table_name='EstadisticasModelosDetalle')
    op.drop_table('EstadisticasModelosDetalle')
    op.drop_index(op.f('ix_EstadisticasModelos_UsuarioId'), table_name='EstadisticasModelos')
    op.drop_index(op.f('ix_EstadisticasModelos_Id'), table_name='EstadisticasModelos')
    op.drop_table('EstadisticasModelos')
    # ### end Alembic commands ###
