"""se quita valor unico en codigo tarrea

Revision ID: 46c7b1e58deb
Revises: 0f41a8cb6b7b
Create Date: 2026-09-14 23:59:42.536741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c7b1e58deb'
down_revision: Union[str, Sequence[str], None] = '0f41a8cb6b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ErroresProcesamientoImagenesPendientes_CodigoTarea'), 'ErroresProcesamientoImagenesPendientes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_ErroresProcesamientoImagenesPendientes_CodigoTarea'), 'ErroresProcesamientoImagenesPendientes', ['CodigoTarea'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
