"""agregar campo de tamanno de img en MovimientosImagenes

Revision ID: 479a55ca445b
Revises: bbc41cd92afc
Create Date: 2026-09-11 23:11:17.318804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479a55ca445b'
down_revision: Union[str, Sequence[str], None] = 'bbc41cd92afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MovimientosGastosImagenes', sa.Column('TamañoImagen', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MovimientosGastosImagenes', 'TamañoImagen')
    # ### end Alembic commands ###
