"""se agrega el rubro de la empresa

Revision ID: 47d021a1f1c0
Revises: 0980d5c838a5
Create Date: 2026-08-21 09:58:45.897407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d021a1f1c0'
down_revision: Union[str, Sequence[str], None] = '0980d5c838a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Empresas', sa.Column('Rubro', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Empresas', 'Rubro')
    # ### end Alembic commands ###
