"""crear_tablas_iniciales

Revision ID: 4b291ef913f2
Revises: 
Create Date: 2026-08-10 22:27:20.770851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b291ef913f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuarios',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('NombreUsuario', sa.String(length=100), nullable=False),
    sa.Column('ApellidoUsuario', sa.String(length=100), nullable=False),
    sa.Column('UserName', sa.String(length=50), nullable=False),
    sa.Column('Correo', sa.String(length=255), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Usuarios_Id'), 'Usuarios', ['Id'], unique=False)
    op.create_index(op.f('ix_Usuarios_UserName'), 'Usuarios', ['UserName'], unique=True)
    op.create_table('SesionesActivas',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('Dispositivo', sa.String(length=255), nullable=False),
    sa.Column('IpConexion', sa.String(length=45), nullable=False),
    sa.Column('FechaConexion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_SesionesActivas_Id'), 'SesionesActivas', ['Id'], unique=False)
    op.create_index(op.f('ix_SesionesActivas_UsuarioId'), 'SesionesActivas', ['UsuarioId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SesionesActivas_UsuarioId'), table_name='SesionesActivas')
    op.drop_index(op.f('ix_SesionesActivas_Id'), table_name='SesionesActivas')
    op.drop_table('SesionesActivas')
    op.drop_index(op.f('ix_Usuarios_UserName'), table_name='Usuarios')
    op.drop_index(op.f('ix_Usuarios_Id'), table_name='Usuarios')
    op.drop_table('Usuarios')
    # ### end Alembic commands ###
