"""models_categorias_empresas

Revision ID: 5397860d938b
Revises: 4b291ef913f2
Create Date: 2026-08-11 22:01:03.215350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5397860d938b'
down_revision: Union[str, Sequence[str], None] = '4b291ef913f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Empresas',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('NombreEmpresa', sa.String(length=200), nullable=False),
    sa.Column('Ruc', sa.String(length=50), nullable=False),
    sa.Column('UrlLogo', sa.String(length=255), nullable=True),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Empresas_Id'), 'Empresas', ['Id'], unique=False)
    op.create_index(op.f('ix_Empresas_Ruc'), 'Empresas', ['Ruc'], unique=True)
    op.create_table('CategoriasGastos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('NombreCategoria', sa.String(length=200), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_CategoriasGastos_Id'), 'CategoriasGastos', ['Id'], unique=False)
    op.create_index(op.f('ix_CategoriasGastos_UsuarioId'), 'CategoriasGastos', ['UsuarioId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CategoriasGastos_UsuarioId'), table_name='CategoriasGastos')
    op.drop_index(op.f('ix_CategoriasGastos_Id'), table_name='CategoriasGastos')
    op.drop_table('CategoriasGastos')
    op.drop_index(op.f('ix_Empresas_Ruc'), table_name='Empresas')
    op.drop_index(op.f('ix_Empresas_Id'), table_name='Empresas')
    op.drop_table('Empresas')
    # ### end Alembic commands ###
