"""eliminar tabla ImagenesEscaneadas

Revision ID: 55da82b6cad8
Revises: fd0113d0d9d5
Create Date: 2026-08-28 00:29:32.835374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55da82b6cad8'
down_revision: Union[str, Sequence[str], None] = 'fd0113d0d9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ImagenesEscaneadas_CodigoProceso'), table_name='ImagenesEscaneadas')
    op.drop_index(op.f('ix_ImagenesEscaneadas_Id'), table_name='ImagenesEscaneadas')
    op.drop_index(op.f('ix_ImagenesEscaneadas_UrlImagen'), table_name='ImagenesEscaneadas')
    op.drop_index(op.f('ix_ImagenesEscaneadas_UsuarioId'), table_name='ImagenesEscaneadas')
    op.drop_table('ImagenesEscaneadas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ImagenesEscaneadas',
    sa.Column('Id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UrlImagen', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('FechaRegistro', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('UsuarioId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('FechaProcesado', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('PendienteEliminacion', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('FechaEliminacion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('CodigoProceso', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], name=op.f('ImagenesEscaneadas_UsuarioId_fkey')),
    sa.PrimaryKeyConstraint('Id', name=op.f('ImagenesEscaneadas_pkey'))
    )
    op.create_index(op.f('ix_ImagenesEscaneadas_UsuarioId'), 'ImagenesEscaneadas', ['UsuarioId'], unique=False)
    op.create_index(op.f('ix_ImagenesEscaneadas_UrlImagen'), 'ImagenesEscaneadas', ['UrlImagen'], unique=True)
    op.create_index(op.f('ix_ImagenesEscaneadas_Id'), 'ImagenesEscaneadas', ['Id'], unique=False)
    op.create_index(op.f('ix_ImagenesEscaneadas_CodigoProceso'), 'ImagenesEscaneadas', ['CodigoProceso'], unique=False)
    # ### end Alembic commands ###
