"""cambios en MovimientosGastosImagenes

Revision ID: 5e1cadf3aaf6
Revises: 2a49594f3da7
Create Date: 2026-08-14 12:36:44.440341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1cadf3aaf6'
down_revision: Union[str, Sequence[str], None] = '2a49594f3da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ImagenesPendientes',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CodigoTarea', sa.String(length=255), nullable=False),
    sa.Column('UrlImagen', sa.String(length=500), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_ImagenesPendientes_CodigoTarea'), 'ImagenesPendientes', ['CodigoTarea'], unique=False)
    op.create_index(op.f('ix_ImagenesPendientes_Id'), 'ImagenesPendientes', ['Id'], unique=False)
    op.create_index(op.f('ix_ImagenesPendientes_UrlImagen'), 'ImagenesPendientes', ['UrlImagen'], unique=True)
    op.create_index(op.f('ix_ImagenesPendientes_UsuarioId'), 'ImagenesPendientes', ['UsuarioId'], unique=False)
    op.alter_column('MovimientosGastosImagenes', 'UrlImagen',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('MovimientosGastosImagenes', 'ReferenciaCola',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MovimientosGastosImagenes', 'ReferenciaCola',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('MovimientosGastosImagenes', 'UrlImagen',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_ImagenesPendientes_UsuarioId'), table_name='ImagenesPendientes')
    op.drop_index(op.f('ix_ImagenesPendientes_UrlImagen'), table_name='ImagenesPendientes')
    op.drop_index(op.f('ix_ImagenesPendientes_Id'), table_name='ImagenesPendientes')
    op.drop_index(op.f('ix_ImagenesPendientes_CodigoTarea'), table_name='ImagenesPendientes')
    op.drop_table('ImagenesPendientes')
    # ### end Alembic commands ###
