"""agregar campo de us active en movimiento gasto

Revision ID: 5e6e08cc5e38
Revises: d62d2e52fd1f
Create Date: 2026-09-13 22:28:28.232513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6e08cc5e38'
down_revision: Union[str, Sequence[str], None] = 'd62d2e52fd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MovimientosGastos', sa.Column('IsActive', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MovimientosGastos', 'IsActive')
    # ### end Alembic commands ###
