"""parametrizaciones_tipo_medio_pago

Revision ID: 66f5de086449
Revises: 3d3a4d8250b9
Create Date: 2026-10-01 23:01:40.678875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f5de086449'
down_revision: Union[str, Sequence[str], None] = '3d3a4d8250b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TiposMediosPagos', sa.Column('SolicitarMarca', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('TiposMediosPagos', sa.Column('SolicitarEntidad', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TiposMediosPagos', 'SolicitarEntidad')
    op.drop_column('TiposMediosPagos', 'SolicitarMarca')
    # ### end Alembic commands ###
