"""tabla de escaneo de imagenes- control de relacion

Revision ID: 6a104a0212db
Revises: 8d83572b0a72
Create Date: 2026-08-27 21:53:05.733110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a104a0212db'
down_revision: Union[str, Sequence[str], None] = '8d83572b0a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
