"""creacion de tabla de envio de correos

Revision ID: 6a51b30cc6d0
Revises: a4c7e91f2b10
Create Date: 2026-09-01 23:03:34.414497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a51b30cc6d0'
down_revision: Union[str, Sequence[str], None] = 'a4c7e91f2b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
