"""se agrega info de modelos utilizados en registros de facturas

Revision ID: 6aa0a7bdfa03
Revises: 39783cf809d9
Create Date: 2026-08-19 09:43:17.059687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa0a7bdfa03'
down_revision: Union[str, Sequence[str], None] = '39783cf809d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MovimientosGastos', sa.Column('ModeloExtraccionDatos', sa.String(length=255), nullable=True))
    op.add_column('MovimientosGastos', sa.Column('ModeloClasificador', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MovimientosGastos', 'ModeloClasificador')
    op.drop_column('MovimientosGastos', 'ModeloExtraccionDatos')
    # ### end Alembic commands ###
