"""Cambio estructura ImagenesReportadas

Revision ID: 6abbf0c145c0
Revises: 8b7b05e0e2c0
Create Date: 2026-09-02 20:44:30.858464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6abbf0c145c0'
down_revision: Union[str, Sequence[str], None] = '8b7b05e0e2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImagenesReportadas', sa.Column('Respuesta', sa.JSON(), nullable=True))
    op.drop_column('ImagenesReportadas', 'ResultadoClasificacion')
    op.drop_column('ImagenesReportadas', 'ResultadoExtraccion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImagenesReportadas', sa.Column('ResultadoExtraccion', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ImagenesReportadas', sa.Column('ResultadoClasificacion', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('ImagenesReportadas', 'Respuesta')
    # ### end Alembic commands ###
