"""estado_entidades_usuario

Revision ID: 84081257792e
Revises: a90f2a4f12ff
Create Date: 2026-10-01 22:37:07.919347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84081257792e'
down_revision: Union[str, Sequence[str], None] = 'a90f2a4f12ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EntidadesUsuarios', sa.Column('IsActive', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EntidadesUsuarios', 'IsActive')
    # ### end Alembic commands ###
