"""codigo_reporte

Revision ID: 8b7b05e0e2c0
Revises: f5604b892b7b
Create Date: 2026-09-02 14:28:19.477049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7b05e0e2c0'
down_revision: Union[str, Sequence[str], None] = 'f5604b892b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImagenesReportadas', sa.Column('CodigoReporte', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_ImagenesReportadas_CodigoReporte'), 'ImagenesReportadas', ['CodigoReporte'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ImagenesReportadas_CodigoReporte'), table_name='ImagenesReportadas')
    op.drop_column('ImagenesReportadas', 'CodigoReporte')
    # ### end Alembic commands ###
