"""creacion de tabla de envio de correos

Revision ID: 8c4422097812
Revises: 1a6ed9fbb0f3
Create Date: 2026-09-01 23:06:15.041427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4422097812'
down_revision: Union[str, Sequence[str], None] = '1a6ed9fbb0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EnvioCorreos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Destinatario', sa.String(length=255), nullable=False),
    sa.Column('Asunto', sa.String(length=255), nullable=False),
    sa.Column('NombreTemplate', sa.String(length=255), nullable=False),
    sa.Column('Data', sa.JSON(), nullable=True),
    sa.Column('ContextKey', sa.String(length=255), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('FechaProcesado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('Procesado', sa.Boolean(), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_EnvioCorreos_Id'), 'EnvioCorreos', ['Id'], unique=False)
    op.create_index(op.f('ix_EnvioCorreos_UsuarioId'), 'EnvioCorreos', ['UsuarioId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_EnvioCorreos_UsuarioId'), table_name='EnvioCorreos')
    op.drop_index(op.f('ix_EnvioCorreos_Id'), table_name='EnvioCorreos')
    op.drop_table('EnvioCorreos')
    # ### end Alembic commands ###
