"""tabla de escaneo de imagenes

Revision ID: 8d83572b0a72
Revises: 2048f95a44fd
Create Date: 2026-08-27 21:05:50.387685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d83572b0a72'
down_revision: Union[str, Sequence[str], None] = '2048f95a44fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ImagenesEscaneadas',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CodigoTarea', sa.String(length=255), nullable=False),
    sa.Column('UrlImagen', sa.String(length=500), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('FechaProcesado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('PendienteEliminacion', sa.Boolean(), nullable=False),
    sa.Column('FechaEliminacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_ImagenesEscaneadas_CodigoTarea'), 'ImagenesEscaneadas', ['CodigoTarea'], unique=False)
    op.create_index(op.f('ix_ImagenesEscaneadas_Id'), 'ImagenesEscaneadas', ['Id'], unique=False)
    op.create_index(op.f('ix_ImagenesEscaneadas_UrlImagen'), 'ImagenesEscaneadas', ['UrlImagen'], unique=True)
    op.create_index(op.f('ix_ImagenesEscaneadas_UsuarioId'), 'ImagenesEscaneadas', ['UsuarioId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ImagenesEscaneadas_UsuarioId'), table_name='ImagenesEscaneadas')
    op.drop_index(op.f('ix_ImagenesEscaneadas_UrlImagen'), table_name='ImagenesEscaneadas')
    op.drop_index(op.f('ix_ImagenesEscaneadas_Id'), table_name='ImagenesEscaneadas')
    op.drop_index(op.f('ix_ImagenesEscaneadas_CodigoTarea'), table_name='ImagenesEscaneadas')
    op.drop_table('ImagenesEscaneadas')
    # ### end Alembic commands ###
