"""creacion de tabla de urls temporales

Revision ID: 9233191359be
Revises: 55da82b6cad8
Create Date: 2026-08-28 00:45:51.654506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9233191359be'
down_revision: Union[str, Sequence[str], None] = '55da82b6cad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UrlsImagenesTemporales',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CodigoProceso', sa.String(length=255), nullable=False),
    sa.Column('UrlImagen', sa.String(length=500), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('FechaProcesado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('PendienteEliminacion', sa.Boolean(), nullable=False),
    sa.Column('FechaEliminacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_UrlsImagenesTemporales_CodigoProceso'), 'UrlsImagenesTemporales', ['CodigoProceso'], unique=False)
    op.create_index(op.f('ix_UrlsImagenesTemporales_Id'), 'UrlsImagenesTemporales', ['Id'], unique=False)
    op.create_index(op.f('ix_UrlsImagenesTemporales_UrlImagen'), 'UrlsImagenesTemporales', ['UrlImagen'], unique=True)
    op.create_index(op.f('ix_UrlsImagenesTemporales_UsuarioId'), 'UrlsImagenesTemporales', ['UsuarioId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UrlsImagenesTemporales_UsuarioId'), table_name='UrlsImagenesTemporales')
    op.drop_index(op.f('ix_UrlsImagenesTemporales_UrlImagen'), table_name='UrlsImagenesTemporales')
    op.drop_index(op.f('ix_UrlsImagenesTemporales_Id'), table_name='UrlsImagenesTemporales')
    op.drop_index(op.f('ix_UrlsImagenesTemporales_CodigoProceso'), table_name='UrlsImagenesTemporales')
    op.drop_table('UrlsImagenesTemporales')
    # ### end Alembic commands ###
