"""campo agregado a MovimientosImagenes para control de error

Revision ID: 98c3693bb8db
Revises: 662466b707cf
Create Date: 2026-08-14 22:36:24.624981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c3693bb8db'
down_revision: Union[str, Sequence[str], None] = '662466b707cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MovimientosGastosImagenes', sa.Column('ErrorUploadImg', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MovimientosGastosImagenes', 'ErrorUploadImg')
    # ### end Alembic commands ###
