"""imagenes_pendientes_medios_pagos

Revision ID: 9b74da1ad548
Revises: 66f5de086449
Create Date: 2026-10-02 22:31:20.997499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b74da1ad548'
down_revision: Union[str, Sequence[str], None] = '66f5de086449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImagenesPendientes', sa.Column('MediosPagos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ImagenesPendientes', 'MediosPagos')
    # ### end Alembic commands ###
