"""agregado tablas de preferencias usuarios

Revision ID: a1436cd6d725
Revises: f30a404b93ae
Create Date: 2026-09-07 21:39:04.524831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1436cd6d725'
down_revision: Union[str, Sequence[str], None] = 'f30a404b93ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Temas',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NombreTema', sa.String(length=200), nullable=False),
    sa.Column('Tipo', sa.String(length=200), nullable=False),
    sa.Column('Descripcion', sa.String(length=500), nullable=True),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Temas_Id'), 'Temas', ['Id'], unique=False)
    op.create_index(op.f('ix_Temas_NombreTema'), 'Temas', ['NombreTema'], unique=True)
    op.create_table('PreferenciasUsuario',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('TemaId', sa.Integer(), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['TemaId'], ['Temas.Id'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_PreferenciasUsuario_Id'), 'PreferenciasUsuario', ['Id'], unique=False)
    op.create_index(op.f('ix_PreferenciasUsuario_TemaId'), 'PreferenciasUsuario', ['TemaId'], unique=False)
    op.create_index(op.f('ix_PreferenciasUsuario_UsuarioId'), 'PreferenciasUsuario', ['UsuarioId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PreferenciasUsuario_UsuarioId'), table_name='PreferenciasUsuario')
    op.drop_index(op.f('ix_PreferenciasUsuario_TemaId'), table_name='PreferenciasUsuario')
    op.drop_index(op.f('ix_PreferenciasUsuario_Id'), table_name='PreferenciasUsuario')
    op.drop_table('PreferenciasUsuario')
    op.drop_index(op.f('ix_Temas_NombreTema'), table_name='Temas')
    op.drop_index(op.f('ix_Temas_Id'), table_name='Temas')
    op.drop_table('Temas')
    # ### end Alembic commands ###
