"""estado_marcas_tarjetas

Revision ID: a90f2a4f12ff
Revises: aa9720f94f30
Create Date: 2026-10-01 22:23:30.188630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90f2a4f12ff'
down_revision: Union[str, Sequence[str], None] = 'aa9720f94f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MarcasTarjetas', sa.Column('IsActive', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MarcasTarjetas', 'IsActive')
    # ### end Alembic commands ###
