"""estructura_medios_pagos

Revision ID: aa9720f94f30
Revises: 46c7b1e58deb
Create Date: 2026-10-01 22:06:24.633697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9720f94f30'
down_revision: Union[str, Sequence[str], None] = '46c7b1e58deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CanalesPagos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('NombreCanal', sa.String(length=200), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_CanalesPagos_Id'), 'CanalesPagos', ['Id'], unique=False)
    op.create_table('EntidadesUsuarios',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('NombreEntidad', sa.String(length=200), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_EntidadesUsuarios_Id'), 'EntidadesUsuarios', ['Id'], unique=False)
    op.create_table('TiposMediosPagos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('NombreTipo', sa.String(length=200), nullable=False),
    sa.Column('EsDebito', sa.Boolean(), nullable=True),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_TiposMediosPagos_Id'), 'TiposMediosPagos', ['Id'], unique=False)
    op.create_table('MarcasTarjetas',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('NombreMarca', sa.String(length=200), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_MarcasTarjetas_Id'), 'MarcasTarjetas', ['Id'], unique=False)
    op.create_index(op.f('ix_MarcasTarjetas_UsuarioId'), 'MarcasTarjetas', ['UsuarioId'], unique=False)
    op.create_table('MediosPagosUsuarios',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('TipoMedioPagoId', sa.Integer(), nullable=False),
    sa.Column('EntidadUsuarioId', sa.Integer(), nullable=True),
    sa.Column('MarcaTarjetaId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EntidadUsuarioId'], ['EntidadesUsuarios.Id'], ),
    sa.ForeignKeyConstraint(['MarcaTarjetaId'], ['MarcasTarjetas.Id'], ),
    sa.ForeignKeyConstraint(['TipoMedioPagoId'], ['TiposMediosPagos.Id'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_MediosPagosUsuarios_EntidadUsuarioId'), 'MediosPagosUsuarios', ['EntidadUsuarioId'], unique=False)
    op.create_index(op.f('ix_MediosPagosUsuarios_Id'), 'MediosPagosUsuarios', ['Id'], unique=False)
    op.create_index(op.f('ix_MediosPagosUsuarios_MarcaTarjetaId'), 'MediosPagosUsuarios', ['MarcaTarjetaId'], unique=False)
    op.create_index(op.f('ix_MediosPagosUsuarios_TipoMedioPagoId'), 'MediosPagosUsuarios', ['TipoMedioPagoId'], unique=False)
    op.create_index(op.f('ix_MediosPagosUsuarios_UsuarioId'), 'MediosPagosUsuarios', ['UsuarioId'], unique=False)
    op.create_table('MovimientosGastosMediosPagos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('MontoMedio', sa.Integer(), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('MovimientoGastoId', sa.Integer(), nullable=False),
    sa.Column('MedioPagoUsuarioId', sa.Integer(), nullable=False),
    sa.Column('CanalPagoId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CanalPagoId'], ['CanalesPagos.Id'], ),
    sa.ForeignKeyConstraint(['MedioPagoUsuarioId'], ['MediosPagosUsuarios.Id'], ),
    sa.ForeignKeyConstraint(['MovimientoGastoId'], ['MovimientosGastos.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_MovimientosGastosMediosPagos_CanalPagoId'), 'MovimientosGastosMediosPagos', ['CanalPagoId'], unique=False)
    op.create_index(op.f('ix_MovimientosGastosMediosPagos_Id'), 'MovimientosGastosMediosPagos', ['Id'], unique=False)
    op.create_index(op.f('ix_MovimientosGastosMediosPagos_MedioPagoUsuarioId'), 'MovimientosGastosMediosPagos', ['MedioPagoUsuarioId'], unique=False)
    op.create_index(op.f('ix_MovimientosGastosMediosPagos_MovimientoGastoId'), 'MovimientosGastosMediosPagos', ['MovimientoGastoId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_MovimientosGastosMediosPagos_MovimientoGastoId'), table_name='MovimientosGastosMediosPagos')
    op.drop_index(op.f('ix_MovimientosGastosMediosPagos_MedioPagoUsuarioId'), table_name='MovimientosGastosMediosPagos')
    op.drop_index(op.f('ix_MovimientosGastosMediosPagos_Id'), table_name='MovimientosGastosMediosPagos')
    op.drop_index(op.f('ix_MovimientosGastosMediosPagos_CanalPagoId'), table_name='MovimientosGastosMediosPagos')
    op.drop_table('MovimientosGastosMediosPagos')
    op.drop_index(op.f('ix_MediosPagosUsuarios_UsuarioId'), table_name='MediosPagosUsuarios')
    op.drop_index(op.f('ix_MediosPagosUsuarios_TipoMedioPagoId'), table_name='MediosPagosUsuarios')
    op.drop_index(op.f('ix_MediosPagosUsuarios_MarcaTarjetaId'), table_name='MediosPagosUsuarios')
    op.drop_index(op.f('ix_MediosPagosUsuarios_Id'), table_name='MediosPagosUsuarios')
    op.drop_index(op.f('ix_MediosPagosUsuarios_EntidadUsuarioId'), table_name='MediosPagosUsuarios')
    op.drop_table('MediosPagosUsuarios')
    op.drop_index(op.f('ix_MarcasTarjetas_UsuarioId'), table_name='MarcasTarjetas')
    op.drop_index(op.f('ix_MarcasTarjetas_Id'), table_name='MarcasTarjetas')
    op.drop_table('MarcasTarjetas')
    op.drop_index(op.f('ix_TiposMediosPagos_Id'), table_name='TiposMediosPagos')
    op.drop_table('TiposMediosPagos')
    op.drop_index(op.f('ix_EntidadesUsuarios_Id'), table_name='EntidadesUsuarios')
    op.drop_table('EntidadesUsuarios')
    op.drop_index(op.f('ix_CanalesPagos_Id'), table_name='CanalesPagos')
    op.drop_table('CanalesPagos')
    # ### end Alembic commands ###
