"""se agrega tamanno de imagen_temporal

Revision ID: bbc41cd92afc
Revises: 3ffb4ae95ac8
Create Date: 2026-09-11 15:49:05.834351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc41cd92afc'
down_revision: Union[str, Sequence[str], None] = '3ffb4ae95ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UrlsImagenesTemporales',
    sa.Column('TamañoImagen', sa.Integer(), nullable=True, server_default='0')
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UrlsImagenesTemporales', 'TamañoImagen')
    # ### end Alembic commands ###
