"""se agrega tamanno en ImagenesPendientes

Revision ID: d62d2e52fd1f
Revises: e82b877aedbd
Create Date: 2026-09-12 08:59:35.402045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62d2e52fd1f'
down_revision: Union[str, Sequence[str], None] = 'e82b877aedbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImagenesPendientes', sa.Column('TamañoImagen', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ImagenesPendientes', 'TamañoImagen')
    # ### end Alembic commands ###
