"""agregar campo IsAdmin a Usuarios

Revision ID: dc92a287f2f6
Revises: 6abbf0c145c0
Create Date: 2026-09-02 23:09:45.642398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc92a287f2f6'
down_revision: Union[str, Sequence[str], None] = '6abbf0c145c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('IsAdmin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Usuarios', 'IsAdmin')
    # ### end Alembic commands ###
