"""agregar campo de id estadisticas en url temporales

Revision ID: e82b877aedbd
Revises: 479a55ca445b
Create Date: 2026-09-11 23:41:38.896793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82b877aedbd'
down_revision: Union[str, Sequence[str], None] = '479a55ca445b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UrlsImagenesTemporales', sa.Column('IdEstadistica', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UrlsImagenesTemporales', 'IdEstadistica')
    # ### end Alembic commands ###
