"""fecha registro en urls de reportadas

Revision ID: f30a404b93ae
Revises: 227fa2a2a0ac
Create Date: 2026-09-03 15:29:01.130364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30a404b93ae'
down_revision: Union[str, Sequence[str], None] = '227fa2a2a0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImagenesReportadasUrls', sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ImagenesReportadasUrls', 'FechaRegistro')
    # ### end Alembic commands ###
