"""Tabla Imagenes Reportadas creada

Revision ID: f5604b892b7b
Revises: 8c4422097812
Create Date: 2026-09-02 14:18:58.230677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5604b892b7b'
down_revision: Union[str, Sequence[str], None] = '8c4422097812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ImagenesReportadas',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UrlImagen', sa.String(length=500), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('ResultadoExtraccion', sa.JSON(), nullable=True),
    sa.Column('ResultadoClasificacion', sa.JSON(), nullable=True),
    sa.Column('Observacion', sa.String(length=1000), nullable=True),
    sa.Column('EstadoResolucion', sa.Enum('Pendiente', 'Resuelto', name='estadoresolucionenum'), nullable=False),
    sa.Column('Resolucion', sa.String(length=1000), nullable=True),
    sa.Column('FechaResolucion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_ImagenesReportadas_Id'), 'ImagenesReportadas', ['Id'], unique=False)
    op.create_index(op.f('ix_ImagenesReportadas_UrlImagen'), 'ImagenesReportadas', ['UrlImagen'], unique=True)
    op.create_index(op.f('ix_ImagenesReportadas_UsuarioId'), 'ImagenesReportadas', ['UsuarioId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ImagenesReportadas_UsuarioId'), table_name='ImagenesReportadas')
    op.drop_index(op.f('ix_ImagenesReportadas_UrlImagen'), table_name='ImagenesReportadas')
    op.drop_index(op.f('ix_ImagenesReportadas_Id'), table_name='ImagenesReportadas')
    op.drop_table('ImagenesReportadas')
    # ### end Alembic commands ###
