"""tabla de escaneo de imagenes- cambio de campos

Revision ID: fd0113d0d9d5
Revises: 6a104a0212db
Create Date: 2026-08-27 22:00:49.074264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0113d0d9d5'
down_revision: Union[str, Sequence[str], None] = '6a104a0212db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImagenesEscaneadas', sa.Column('CodigoProceso', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_ImagenesEscaneadas_CodigoTarea'), table_name='ImagenesEscaneadas')
    op.create_index(op.f('ix_ImagenesEscaneadas_CodigoProceso'), 'ImagenesEscaneadas', ['CodigoProceso'], unique=False)
    op.drop_column('ImagenesEscaneadas', 'CodigoTarea')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImagenesEscaneadas', sa.Column('CodigoTarea', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_ImagenesEscaneadas_CodigoProceso'), table_name='ImagenesEscaneadas')
    op.create_index(op.f('ix_ImagenesEscaneadas_CodigoTarea'), 'ImagenesEscaneadas', ['CodigoTarea'], unique=False)
    op.drop_column('ImagenesEscaneadas', 'CodigoProceso')
    # ### end Alembic commands ###
