"""cambios en sesiones activas

Revision ID: fe61a63ce20e
Revises: c47da8e37ec7
Create Date: 2026-08-25 00:17:02.756976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe61a63ce20e'
down_revision: Union[str, Sequence[str], None] = 'c47da8e37ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SesionesActivas', sa.Column('SessionId', sa.String(length=36), nullable=False))
    op.add_column('SesionesActivas', sa.Column('EsMovil', sa.Boolean(), nullable=False))
    op.add_column('SesionesActivas', sa.Column('Activa', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_SesionesActivas_SessionId'), 'SesionesActivas', ['SessionId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SesionesActivas_SessionId'), table_name='SesionesActivas')
    op.drop_column('SesionesActivas', 'Activa')
    op.drop_column('SesionesActivas', 'EsMovil')
    op.drop_column('SesionesActivas', 'SessionId')
    # ### end Alembic commands ###
